// ============================================================================
//  数据层：肌肉分组映射、动作库、肩痛模块
//  肌肉 match[] = body.glb 节点名（小写）子串规则；命中即归入该组
// ============================================================================

export const MUSC = {
  // 上肢 / 肩 / 胸背
  pec:    { cn:"胸大肌",       lat:"Pectoralis major",   region:"chestF", match:["pectoralis major"] },
  deltA:  { cn:"三角肌前束",   lat:"Deltoid (ant.)",     region:"shoulder", match:["clavicular part of deltoid"] },
  deltM:  { cn:"三角肌中束",   lat:"Deltoid (mid.)",     region:"shoulder", match:["acromial part of deltoid"] },
  deltP:  { cn:"三角肌后束",   lat:"Deltoid (post.)",    region:"shoulderB", match:["scapular spinal part of deltoid"] },
  bic:    { cn:"肱二头肌",     lat:"Biceps brachii",     region:"armF", match:["biceps brachii"] },
  brach:  { cn:"肱肌",         lat:"Brachialis",         region:"armF", match:["brachialis"] },
  tri:    { cn:"肱三头肌",     lat:"Triceps brachii",    region:"armB", match:["triceps brachii"] },
  forearmF:{cn:"前臂屈肌群",   lat:"Forearm flexors",    region:"armF", match:["flexor carpi","flexor digitorum superficialis","flexor digitorum profundus","palmaris longus","pronator teres","flexor pollicis longus"] },
  forearmE:{cn:"前臂伸肌群",   lat:"Forearm extensors",  region:"armB", match:["extensor carpi","extensor digitorum","brachioradialis"] },
  lat:    { cn:"背阔肌",       lat:"Latissimus dorsi",   region:"back", match:["latissimus dorsi"] },
  trapU:  { cn:"斜方肌上部",   lat:"Upper trapezius",    region:"back", match:["descending part of trapezius"] },
  trapM:  { cn:"斜方肌中下部", lat:"Mid/low trapezius",  region:"back", match:["transverse part of trapezius","ascending part of trapezius"] },
  rhom:   { cn:"菱形肌",       lat:"Rhomboids", deep:true, region:"back", match:["rhomboid"] },
  teresMaj:{cn:"大圆肌",       lat:"Teres major",        region:"back", match:["teres major"] },
  serr:   { cn:"前锯肌",       lat:"Serratus anterior",  region:"chestF", match:["serratus anterior"] },
  levscap:{ cn:"肩胛提肌",     lat:"Levator scapulae", deep:true, region:"back", match:["levator scapulae"] },
  // 核心
  abs:    { cn:"腹直肌",       lat:"Rectus abdominis",   region:"chestF", match:["rectus abdominis"] },
  obl:    { cn:"腹斜肌",       lat:"Obliques",           region:"chestF", match:["abdominal oblique"] },
  erec:   { cn:"竖脊肌",       lat:"Erector spinae", deep:true, region:"back", match:["iliocostalis","longissimus thoracis","longissimus#","spinalis"] },
  scm:    { cn:"胸锁乳突肌",   lat:"SCM",                region:"shoulder", match:["sternocleidomastoid"] },
  // 下肢
  glut:   { cn:"臀大肌",       lat:"Gluteus maximus",    region:"legsB", match:["gluteus maximus"] },
  glutM:  { cn:"臀中肌",       lat:"Gluteus med/min",    region:"legsB", match:["gluteus medius","gluteus minimus"] },
  quad:   { cn:"股四头肌",     lat:"Quadriceps",         region:"legsF", match:["rectus femoris","vastus lateralis","vastus medialis","vastus intermedius"] },
  ham:    { cn:"腘绳肌",       lat:"Hamstrings",         region:"legsB", match:["biceps femoris","semitendinosus","semimembranosus"] },
  add:    { cn:"内收肌群",     lat:"Adductors",          region:"legsF", match:["adductor magnus","adductor longus","adductor brevis","gracilis","pectineus"] },
  calf:   { cn:"小腿三头肌",   lat:"Gastroc/Soleus",     region:"legsB", match:["gastrocnemius","soleus"] },
  tib:    { cn:"胫骨前肌",     lat:"Tibialis ant.",      region:"legsF", match:["tibialis anterior"] },
  // 肩袖（深层）
  supra:  { cn:"冈上肌",       lat:"Supraspinatus", deep:true, region:"shoulderB", match:["supraspinatus"] },
  infra:  { cn:"冈下肌",       lat:"Infraspinatus", deep:true, region:"shoulderB", match:["infraspinatus"] },
  teres:  { cn:"小圆肌",       lat:"Teres minor", deep:true, region:"shoulderB", match:["teres minor"] },
  subsc:  { cn:"肩胛下肌",     lat:"Subscapularis", deep:true, region:"shoulder", match:["subscapularis"] },
};

// 相机预设区域 → 供动作/肌肉聚焦
export const REGION_CAM = {
  chestF:  { view:"front", part:"upper" },
  shoulder:{ view:"front", part:"upper" },
  shoulderB:{view:"back",  part:"upper" },
  back:    { view:"back",  part:"upper" },
  armF:    { view:"front", part:"upper" },
  armB:    { view:"back",  part:"upper" },
  legsF:   { view:"front", part:"lower" },
  legsB:   { view:"back",  part:"lower" },
  full:    { view:"front", part:"full" },
};

export const GROUPS = [["chest","胸"],["back","背"],["shoulder","肩"],["legs","腿"],["arms","臂"],["core","核心"]];

// 动作库。m:[muscleId, role]; cam:相机预设; cyc:{c:向心提示, e:离心提示}
export const EX = [
  {id:"bench", g:"chest", name:"杠铃卧推", cam:"chestF",
    m:[["pec","primary"],["deltA","synergist"],["tri","synergist"],["serr","stabilizer"]],
    cue:["肩胛后缩下沉、贴凳固定","小臂始终垂直地面，杠触及乳线附近","脚踩实、臀不离凳"],
    err:["肘完全外展90°易撞击肩关节","下放弹胸借力","含胸塌肩失去稳定"],
    cyc:{c:"呼气推起",e:"吸气下放"}},
  {id:"incline", g:"chest", name:"上斜卧推", cam:"chestF",
    m:[["pec","primary"],["deltA","primary"],["tri","synergist"]],
    cue:["椅背约30°，别过高变肩推","杠触及锁骨下方","保持肩胛稳定"],
    err:["角度过大主要练成肩","起桥过度失去上胸刺激"],
    cyc:{c:"呼气推起",e:"吸气下放"}},
  {id:"fly", g:"chest", name:"哑铃飞鸟", cam:"chestF",
    m:[["pec","primary"],["deltA","synergist"],["bic","stabilizer"]],
    cue:["肘微屈固定，画弧下放","感受胸部拉伸后夹","顶峰略停"],
    err:["肘伸直变卧推","下放过深拉扯肩前侧"],
    cyc:{c:"呼气夹胸",e:"吸气展开"}},
  {id:"dip", g:"chest", name:"双杠臂屈伸", cam:"chestF",
    m:[["pec","primary"],["tri","primary"],["deltA","synergist"]],
    cue:["前倾偏胸、直立偏三头","下放到肩略低于肘","控制离心"],
    err:["下放过深压迫肩前","耸肩失去稳定"],
    cyc:{c:"呼气撑起",e:"吸气下放"}},

  {id:"pullup", g:"back", name:"引体向上", cam:"back",
    m:[["lat","primary"],["bic","synergist"],["trapM","synergist"],["rhom","stabilizer"],["teresMaj","synergist"]],
    cue:["先沉肩、再拉肘向下后","胸口靠近杠","控制离心到直臂"],
    err:["耸肩发力伤肩袖","借力摆荡","不完整行程"],
    cyc:{c:"呼气拉起",e:"吸气下放"}},
  {id:"pulldown", g:"back", name:"高位下拉", cam:"back",
    m:[["lat","primary"],["bic","synergist"],["trapM","synergist"],["rhom","stabilizer"],["teresMaj","synergist"]],
    cue:["坐稳、略后倾","拉杆至锁骨、肘向下","顶峰挤背"],
    err:["身体过度后仰变划船","靠惯性","握太宽减行程"],
    cyc:{c:"呼气下拉",e:"吸气还原"}},
  {id:"bbrow", g:"back", name:"杠铃划船", cam:"back",
    m:[["lat","primary"],["rhom","primary"],["deltP","synergist"],["trapM","synergist"],["erec","stabilizer"],["bic","synergist"]],
    cue:["髋铰链前倾约45°、背挺直","拉向下腹、挤肩胛","核心收紧护腰"],
    err:["圆背伤腰","用惯性甩起","拉太高变耸肩"],
    cyc:{c:"呼气拉回",e:"吸气伸展"}},
  {id:"cablerow", g:"back", name:"坐姿划船", cam:"back",
    m:[["lat","primary"],["rhom","primary"],["trapM","synergist"],["deltP","synergist"],["bic","synergist"]],
    cue:["挺胸沉肩、肘贴身后拉","顶峰夹背1秒","离心慢放不塌肩"],
    err:["身体前后摇摆借力","耸肩","含胸"],
    cyc:{c:"呼气拉回",e:"吸气伸展"}},
  {id:"deadlift", g:"back", name:"硬拉", cam:"back",
    m:[["glut","primary"],["ham","primary"],["erec","primary"],["quad","synergist"],["lat","stabilizer"],["trapM","stabilizer"]],
    cue:["杠贴胫、肩略过杠","核心绷紧、背中立","髋膝同步伸展锁定"],
    err:["圆背拉起风险高","杠离身重心前移","超伸后仰顶腰"],
    cyc:{c:"呼气拉起",e:"吸气下放"}},

  {id:"ohp", g:"shoulder", name:"站姿推举", cam:"shoulder",
    m:[["deltA","primary"],["deltM","primary"],["tri","synergist"],["trapU","synergist"],["subsc","stabilizer"]],
    cue:["杠位于掌根、核心收紧","头略后避杠再顺势前移","锁定时耳侧过杠"],
    err:["塌腰借力变斜板","肘过度外展撞击","耸肩过早"],
    cyc:{c:"呼气上推",e:"吸气下放"}},
  {id:"latraise", g:"shoulder", name:"哑铃侧平举", cam:"shoulder",
    m:[["deltM","primary"],["supra","synergist"],["trapU","stabilizer"]],
    cue:["肘略屈、小指略高领","抬到肩高即可","离心慢放"],
    err:["耸肩借斜方","甩动惯性","过肩高易撞击"],
    cyc:{c:"呼气抬起",e:"吸气放下"}},
  {id:"facepull", g:"shoulder", name:"面拉", cam:"shoulderB",
    m:[["deltP","primary"],["rhom","primary"],["trapM","synergist"],["infra","synergist"],["teres","stabilizer"]],
    cue:["绳拉向额前、肘高于腕","外旋分手、挤肩胛","轻重量高次数"],
    err:["耸肩","重量过大变划船","肘下沉失去外旋"],
    cyc:{c:"呼气后拉",e:"吸气回放"}},
  {id:"reardelt", g:"shoulder", name:"反向飞鸟", cam:"shoulderB",
    m:[["deltP","primary"],["rhom","synergist"],["trapM","synergist"],["infra","stabilizer"]],
    cue:["前倾固定、肘微屈","向两侧画弧、挤肩胛","顶峰略停"],
    err:["耸肩代偿","肘伸直变别的","惯性甩"],
    cyc:{c:"呼气展开",e:"吸气回收"}},

  {id:"squat", g:"legs", name:"杠铃深蹲", cam:"legsF",
    m:[["quad","primary"],["glut","primary"],["erec","synergist"],["ham","synergist"],["add","stabilizer"]],
    cue:["杠位稳、核心绷","髋膝同步、膝对脚尖","蹲至大腿平行或更低"],
    err:["膝内扣","塌腰或圆背","重心过度前倾"],
    cyc:{c:"呼气蹬起",e:"吸气下蹲"}},
  {id:"legpress", g:"legs", name:"倒蹬(腿举)", cam:"legsF",
    m:[["quad","primary"],["glut","primary"],["ham","synergist"],["add","stabilizer"]],
    cue:["脚位适中、腰贴垫","下放到膝约90°","不锁死膝关节"],
    err:["腰离垫圆下背","行程过深翻臀","锁膝顶伤"],
    cyc:{c:"呼气蹬出",e:"吸气回收"}},
  {id:"rdl", g:"legs", name:"罗马尼亚硬拉", cam:"legsB",
    m:[["ham","primary"],["glut","primary"],["erec","synergist"],["lat","stabilizer"]],
    cue:["微屈膝固定、髋向后推","杠贴腿下滑至拉伸感","挺髋起、不超伸"],
    err:["圆背","变成屈膝深蹲","顶端过度后仰"],
    cyc:{c:"呼气挺髋",e:"吸气下放"}},
  {id:"legcurl", g:"legs", name:"腿弯举", cam:"legsB",
    m:[["ham","primary"],["calf","stabilizer"]],
    cue:["髋贴垫、脚背勾","勾到底顶峰收缩","离心慢放"],
    err:["抬臀借力","行程不足","甩动"],
    cyc:{c:"呼气勾腿",e:"吸气伸直"}},
  {id:"legext", g:"legs", name:"腿屈伸", cam:"legsF",
    m:[["quad","primary"]],
    cue:["膝对齐转轴、坐稳","伸直顶峰略停","慢放控制"],
    err:["甩动惯性","锁膝猛顶","臀离座"],
    cyc:{c:"呼气伸膝",e:"吸气回落"}},
  {id:"hipthrust", g:"legs", name:"臀推", cam:"legsB",
    m:[["glut","primary"],["ham","synergist"],["quad","synergist"],["erec","stabilizer"]],
    cue:["肩胛靠凳、下巴微收","顶髋至躯干与地平行","顶峰夹臀1秒"],
    err:["过度挺腰用腰代臀","脚位过远变腘绳","行程不足"],
    cyc:{c:"呼气顶髋",e:"吸气下放"}},
  {id:"calf", g:"legs", name:"站姿提踵", cam:"legsB",
    m:[["calf","primary"]],
    cue:["前脚掌踩稳、缓慢","顶峰充分提起停顿","离心下放到拉伸"],
    err:["弹震借力","行程短","身体前后晃"],
    cyc:{c:"呼气提踵",e:"吸气下放"}},

  {id:"curl", g:"arms", name:"哑铃弯举", cam:"armF",
    m:[["bic","primary"],["brach","synergist"],["forearmF","synergist"]],
    cue:["肘固定贴身","弯举顶峰收紧","离心慢放到直臂"],
    err:["摆动借力","肘前移","没放到底"],
    cyc:{c:"呼气弯举",e:"吸气下放"}},
  {id:"triext", g:"arms", name:"绳索下压", cam:"armB",
    m:[["tri","primary"],["forearmE","stabilizer"]],
    cue:["肘固定夹身两侧","下压至完全伸直","顶峰收紧三头"],
    err:["肘外张耸肩","身体前压借力","行程不足"],
    cyc:{c:"呼气下压",e:"吸气回收"}},
  {id:"hammer", g:"arms", name:"锤式弯举", cam:"armF",
    m:[["brach","primary"],["bic","primary"],["forearmF","primary"]],
    cue:["中立握、拇指朝上","肘固定弯举","控制离心"],
    err:["借力甩","肘乱动"],
    cyc:{c:"呼气弯举",e:"吸气下放"}},

  {id:"plank", g:"core", name:"平板支撑", cam:"chestF",
    m:[["abs","primary"],["obl","synergist"],["erec","stabilizer"],["glut","stabilizer"]],
    cue:["肘肩垂直、身体一条线","收紧核心与臀","别塌腰或撅臀"],
    err:["塌腰压下背","撅臀卸力","憋气"],
    cyc:{c:"持续收紧",e:"保持呼吸"}},
  {id:"crunch", g:"core", name:"卷腹", cam:"chestF",
    m:[["abs","primary"],["obl","synergist"]],
    cue:["下背贴地、卷起上背","呼气收紧腹","慢放不完全落地"],
    err:["用脖子拉头","靠惯性弹","扯颈椎"],
    cyc:{c:"呼气卷起",e:"吸气下放"}},
  {id:"woodchop", g:"core", name:"绳索转体", cam:"chestF",
    m:[["obl","primary"],["abs","synergist"],["deltA","stabilizer"]],
    cue:["以核心带动旋转","手臂随躯干、别只甩手","控制回程"],
    err:["只用手臂","腰椎过度扭转","速度失控"],
    cyc:{c:"呼气转体",e:"吸气回位"}},
];

// ============================================================================
//  肩痛模块：结构 → 可高亮的模型肌肉 + 科普信息（教育参考，非诊断）
// ============================================================================
export const SH_ZONES = [
  { id:"subacr", name:"肩峰下 / 外侧（最常见）", highlight:["supra","deltM"],
    layers:[["浅层","三角肌中束"],["中层","肩峰下滑囊"],["深层","冈上肌腱、肩峰下间隙"]],
    problems:[
      {t:"肩峰下撞击综合征", sev:"hi", why:"过顶反复、肩胛节律差、圆肩", sign:"疼痛弧 60–120° 抬臂中段最痛，侧举/过顶推诱发，夜间侧睡痛"},
      {t:"肩峰下滑囊炎", sev:"mid", why:"撞击继发或急性劳损", sign:"外侧钝痛+压痛，抬臂痛，休息略缓"}],
    tests:{do:["Neer：手臂内旋被动上举，外侧痛→阳性提示","Hawkins：屈肘90°内旋下压"], avoid:["直立侧平举过肩、宽握过顶推、耸肩发力"]}},
  { id:"supra", name:"冈上肌腱止点", highlight:["supra"],
    layers:[["浅层","三角肌、肩峰"],["中层","肩峰下滑囊"],["深层","冈上肌腱（止于大结节）"]],
    problems:[
      {t:"冈上肌腱病 / 部分撕裂", sev:"hi", why:"撞击慢性磨损、退变、外伤", sign:"抬臂无力痛，空罐试验痛/无力，夜间痛，可能抬不起"},
      {t:"钙化性肌腱炎", sev:"mid", why:"腱内钙盐沉积", sign:"急性剧痛，特定角度卡住"}],
    tests:{do:["空罐(Empty can)：拇指向下30°前屈抗阻，痛/无力→阳性提示"], avoid:["过顶大重量、侧平举过肩、力竭过顶动作"]}},
  { id:"infra", name:"冈下 / 小圆（肩袖后）", highlight:["infra","teres"],
    layers:[["浅层","三角肌后、斜方中部"],["中层","冈下肌、小圆肌肌腹"],["深层","肩胛骨冈下窝、盂肱后囊"]],
    problems:[
      {t:"冈下肌 / 小圆肌腱病", sev:"mid", why:"外旋肌群薄弱+过用", sign:"外旋抗阻痛/无力，后侧深压痛"},
      {t:"肩袖后侧撕裂", sev:"hi", why:"退变或外伤", sign:"外旋明显无力，抬举受限"}],
    tests:{do:["外旋抗阻(0°位)：肘贴身抗阻外旋，痛/无力→阳性提示"], avoid:["大重量过顶、外旋肌力弱时硬冲拉类重量"]}},
  { id:"bicgroove", name:"结节间沟（二头长头腱）", highlight:["bic","deltA"],
    layers:[["浅层","三角肌前束"],["中层","肱二头肌长头腱及腱鞘"],["深层","肱骨结节间沟"]],
    problems:[
      {t:"肱二头肌长头腱炎", sev:"mid", why:"过顶/拉类反复摩擦、稳定性不足", sign:"沟槽处压痛，弯举、上举、抗阻屈肘痛，可能弹响"},
      {t:"SLAP / 上盂唇问题", sev:"hi", why:"投掷、跌倒撑手、大重量过顶", sign:"深部酸痛+交锁感，过顶发力痛"}],
    tests:{do:["Speed：屈肘抗阻前举，沟槽痛→阳性提示","Yergason：抗阻旋后屈肘"], avoid:["大重量弯举、过顶推、下放过深的卧推/飞鸟"]}},
  { id:"acj", name:"肩锁关节（肩顶）", highlight:["deltA","trapU"],
    layers:[["浅层","皮肤 / 三角肌前缘"],["中层","肩锁韧带、关节囊"],["深层","锁骨外端与肩峰构成的肩锁关节"]],
    problems:[
      {t:"肩锁关节炎 / 分离", sev:"mid", why:"关节退变或摔跌撞伤", sign:"点状压痛正好在关节处，水平内收(手摸对侧肩)时加重，卧推、双杠可诱发"},
      {t:"远端锁骨骨溶解", sev:"lo", why:"大重量卧推长期负荷", sign:"卧推后关节隐痛，休息缓解"}],
    tests:{do:["水平内收挤压：患侧手搭对侧肩，关节处痛→阳性提示"], avoid:["宽握卧推、双杠下沉过深、上斜推顶峰"]}},
  { id:"scap", name:"肩胛内侧缘 / 内上角", highlight:["rhom","levscap","trapM"],
    layers:[["浅层","斜方肌中下部"],["中层","菱形肌"],["深层","肩胛提肌止点、肩胛内侧缘"]],
    problems:[
      {t:"肩胛提肌 / 菱形肌劳损", sev:"lo", why:"久坐圆肩、耸肩发力、姿势差", sign:"内上角酸胀点，颈肩连接处紧，按压舒服"},
      {t:"肩胛动力障碍(翼状肩)", sev:"mid", why:"前锯肌无力、神经因素", sign:"推起时肩胛外翻/内缘翘起，控制差"}],
    tests:{do:["靠墙俯卧撑观察肩胛是否翘起","改善胸椎灵活+前锯激活"], avoid:["持续耸肩训练、长时间圆肩伏案"]}},
  { id:"postdelt", name:"三角肌后 / 腋后", highlight:["deltP","teresMaj"],
    layers:[["浅层","三角肌后束"],["中层","小圆肌、大圆肌"],["深层","盂肱关节后囊"]],
    problems:[
      {t:"后束/小圆肌劳损", sev:"lo", why:"拉类容量大、面拉反飞过量", sign:"后侧酸痛压痛，水平外展抗阻痛"},
      {t:"盂肱关节后囊紧张", sev:"mid", why:"长期内旋姿势、投掷", sign:"内旋活动受限(GIRD)，跨体内收痛"}],
    tests:{do:["跨体内收评估：内旋受限侧提示后囊紧"], avoid:["过量反向飞鸟、极限内旋拉伸初期"]}},
];

export const SH_REDFLAGS = [
  "外伤后立即剧痛、畸形或无法活动",
  "持续夜间静息痛、进行性加重",
  "手臂麻木、刺痛或放射到手（可能颈椎/神经）",
  "明显无力，抬不起手臂（疑肩袖大撕裂）",
  "红肿发热伴发烧（疑感染）",
];

export const RLABEL = { primary:"主动肌", synergist:"协同肌", stabilizer:"稳定肌" };
